name: Run API Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman HTML Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run Outback_Full_Order_Flow.postman_collection.json \
            --reporters cli,junit,json,htmlextra \
            --reporter-junit-export junitReport.xml \
            --reporter-htmlextra-export testReport.html

      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: testReport.html
